/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.core.Ollama_Interface;

public class App {

  public static void main(String[] args) {
    Ollama_Interface ollama = new Ollama_Interface("http://100.102.80.23", "11434", "gemma4", true);
    ollama.generateResponse("Hello World!");

  }
}
